AWSTemplateFormatVersion: '2010-09-09'
Description: 'CF docker host CloudFormation template EC2 Bastion | v2.1'

Parameters:
  ClusterName:
    Description: 'Ex.: a1, t4, b3 ou x9'
    Type: String
    AllowedPattern: '^[a-z]{1}[a-zA-Z0-9]{1,10}$'

Mappings:
  RegionMap:
    us-east-1:
      Amix8664: "ami-053b0d53c279acc90"    # Ubuntu 22.04
    us-west-2:
      Amix8664: "ami-03f65b8614a860c29" # Ubuntu 22.04 LTS
#
Resources:
  sgladocker:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionMap, !Ref AWS::Region, Amix8664 ]
      InstanceType: "t3a.small"
      KeyName: !Sub 'chavepem'
      SubnetId: !ImportValue
        Fn::Sub: "comentarios-${ClusterName}-vpc::PublicSubnet1"
      Ipv6AddressCount: 1
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: "comentarios-${ClusterName}-vpc::BackendSG"
        - !ImportValue
          Fn::Sub: "comentarios-${ClusterName}-vpc::BastionSG"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          fallocate -l 1G /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo "/swapfile none swap sw 0 0" >> /etc/fstab
          apt-get update
          apt-get -y install ca-certificates curl gnupg awscli
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
          aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
          aws configure set region ${AWS_DEFAULT_REGION}
          sudo usermod -aG docker ubuntu