name: Docker Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # replace with your AWS region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        chmod +x version.sh
        ./version.sh -v Hotfix
      env:
        GIT_AUTHOR_NAME: williamsjunior
        GIT_AUTHOR_EMAIL: felis.linux@gmail.com

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: desafiodevops  # replace with your ECR repository name
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Deploy docker image to EC2
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: desafiodevops
        IMAGE_TAG: ${{ github.sha }}
        AWS_DEFAULT_REGION: us-east-2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: EC2_SSH_KEY,REGISTRY,REPOSITORY,IMAGE_TAG,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_REGION
        script: |-
          sudo apt update
          sudo docker stop comentarios || true
          sudo docker rm comentarios || true
          sudo docker pull $REGISTRY/$REPOSITORY:latest
          sudo docker run -d --name comentarios -p 8000:8000 $REGISTRY/$REPOSITORY:latest